### ISSUE TITLE
[FEATURE] 게시판 서비스

### ISSUE THREAD

**Issue by Anyeon00** [prgrms-be-devcourse/NBE1_2_Team06#11]
## 🌴 작업 브랜치 
feature/posts-service
``
## 💼 TASK 개요 
게시판 관련 서비스를 개발한다
지역 내 커뮤니티, 내 게시글
- 게시글
- 댓글
- 좋아요

## ✅ TODO 및 진행현황 

- [x] #15
- [ ] 좋아요 추가 기능
- [ ] 지역 커뮤니티 게시글 호출 API 기능
- [ ] 내 게시글 호출 API 기능
- [ ] 성능 개선 리팩토링

**Comment by JiwonKKang** [comment]
형석님 이슈의 단위가 너무 큰거같아요!

좀더 작은 단위로 아래 TODO에 쓰신 단위로 이슈 발행하면 딱 좋을거 같습니다!

**Comment by Anyeon00** [comment]
아 넵 알겠습니다!
