### ISSUE TITLE
[FEATURE] 응급실 데이터 저장

### ISSUE THREAD

**Issue by LJW22222** [prgrms-be-devcourse/NBE1_2_Team06#24]
## 🌴 작업 브랜치 
feature/emergency-data
``

## 💼 TASK 개요 
전국 각지의 응급실 고유 ID를 사용해 각각의 병원 정보를 공공 IP에서 가져와 DB에 저장

## ✅ TODO 및 진행현황 

- [x] 전국 각지 응급실 데이터 가져오기
- [x] 응급실 데이터 정제 밎 DB 저장
- [x] 외상센터 데이터 정제 및 DB 저장
- [x] 응급실 데이터( 외상센터, 응급실 통합 ) 제공 API
- [x] 전체적인 테스트
