### ISSUE TITLE
[REFACTOR] 회원가입, 로그인 관련 임시 구현 리팩토링

### ISSUE THREAD

**Issue by s0o0bn** [prgrms-be-devcourse/NBE1_2_Team06#35]
## 🌴 작업 브랜치 

`refactor/auth`

## 💼 TASK 개요 

- 기존 의료 관계자 회원 가입 구현 시 병원, 면허 연관 관계 임시로 넘어갔던 부분 수정
- Spring Security 통해 비밀번호 crypto 적용
- 기본, 소셜 로그인 시 JWT 토큰 발급 적용

## ✅ TODO 및 진행현황 

- [x] `MedicalPersonInfo`에 `EmergencyRoom`, `FileMetaData` 추가
- [x] Spring Security `PasswordEncoder` 적용
- [x] 로그인 시 JWT 토큰 발급 적용
- [x] 의료 관계자 인증 API 분리

**Comment by s0o0bn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [회원 가입, 로그인 구체화](https://trello.com/c/BLmP3yRX/31-%ED%9A%8C%EC%9B%90-%EA%B0%80%EC%9E%85-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EA%B5%AC%EC%B2%B4%ED%99%94)
