### ISSUE TITLE
[FEATURE] 챗봇 구현

### ISSUE THREAD

**Issue by s0o0bn** [prgrms-be-devcourse/NBE1_2_Team06#38]
## 🌴 작업 브랜치 

`feature/chatbot`

## 💼 TASK 개요 

상황별 응급 처치 매뉴얼을 기반으로 하는 RAG 챗봇 구현

> 현재 임시로 연결한 Vector DB가 문제가 많아, 제대로 된 데이터 수집해서 재구축 필요......

## ✅ TODO 및 진행현황 

- [x] 응급처치 매뉴얼 데이터 수집
- [x] 벡터 DB 구축
- [x] Spring AI로 LLM API 연동
- [x] SSE 기반 챗봇 시스템 구현
- [x] 사용자 대화 기록 캐싱 (`ChatMemory` 적용)

**Comment by s0o0bn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [챗봇](https://trello.com/c/L5J2ne2l/28-%EC%B1%97%EB%B4%87)
