### ISSUE TITLE
[FEATURE] 알림 시스템 구현

### ISSUE THREAD

**Issue by s0o0bn** [prgrms-be-devcourse/NBE1_2_Team06#62]
## 🌴 작업 브랜치 

`feature/notification`

## 💼 TASK 개요 

- 게시글에 댓글이 달렸을 때 게시글 작성자에게 알림
- (응급실 즐겨찾기한 사용자들에게 공지사항 등록될 시 알림)
   - 한 번에 다수의 사용자에게 모두 알림을 보내야 함
   - 까다로운 작업이 될 것 같아서 시간이 좀 필요할 듯함

## ✅ TODO 및 진행현황 

- [x] 단순 SSE + 이벤트 처리로 알림 구현
- [x] 과거 알림 기록 조회 구현
- [x] 알림 읽음 여부 적용
- [x] Redis pub/sub 적용
