### ISSUE TITLE
[FEATURE] 사용자 회원 가입 기능 구현

### ISSUE THREAD

**Issue by s0o0bn** [prgrms-be-devcourse/NBE1_2_Team06#7]
## 🌴 작업 브랜치 

`feature/signup`

## 💼 TASK 개요 

일반 사용자와 의료 관계자 회원 가입 기능 구현

- 일반 사용자는 별도의 승인 절차 없이 바로 가입 처리
- 의료 관계자는 면허 증명서와 함께 가입 신청 후 대기 상태
    - 이후에 관리자가 가입 승인 처리

## ✅ TODO 및 진행현황 

- [x] 일반 사용자 회원가입 구현
- [x] 의료 관계자 가입 신청 구현
- [x] 대기 상태의 의료 관계자 조회 구현
- [x] 관계자의 가입 신청 승인 구현
- [x] 단위 테스트 작성

**Comment by s0o0bn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [회원가입](https://trello.com/c/5EhqTClH/23-%ED%9A%8C%EC%9B%90%EA%B0%80%EC%9E%85)
