### ISSUE TITLE
[TEST] 게시글 관련 기능 컴포넌트 테스트 작성

### ISSUE THREAD

**Issue by Anyeon00** [prgrms-be-devcourse/NBE1_2_Team06#72]
## 🌴 작업 브랜치 
test/post

## 💼 TASK 개요 
게시글 관련 서비스 테스트 작성

## ✅ TODO 및 진행현황 

- [x] 게시글 서비스 테스트
- [x] 댓글 서비스 테스트
- [x] 좋아요 서비스 테스트
