### ISSUE TITLE
[TEST] API 및 Repository 테스트 작성

### ISSUE THREAD

**Issue by s0o0bn** [prgrms-be-devcourse/NBE1_2_Team06#86]
## 🌴 작업 브랜치 

`feature/api-domain-test`

## 💼 TASK 개요 

- API MockMvc 테스트 작성
- DataJpaTest 작성

## ✅ TODO 및 진행현황 

- [ ] Auth 관련 API 테스트
- [ ] User 관련 API 테스트
- [ ] Notification 관련 API 테스트
- [ ] Chatbot 관련 API 테스트
- [ ] Custom Repository 메서드 테스트
