### ISSUE TITLE
[FEATURE] 챗봇 화면 구현

### ISSUE THREAD

**Issue by s0o0bn** [prgrms-be-devcourse/NBE1_2_Team06#90]
## 🌴 작업 브랜치 

`feature/vue-chatbot`

## 💼 TASK 개요 

- 메인 화면에서 접근 가능한 챗봇 창 구현

## ✅ TODO 및 진행현황 

- [x] 챗봇 프롬프트 개선
- [x] 단순 로딩 챗봇 구현
- [x] GPT처럼 타이핑 효과 적용
